# use ubuntu imagte
image: ubuntu:latest

# dependencies
before_script:
    - apt-get update
    - apt-get install -y software-properties-common
    - echo "Europe/Zurich" > /etc/timezone    
    - dpkg-reconfigure -f noninteractive tzdata
    - apt-get install -y python3-pip python3-numpy python3-matplotlib
#    - pip3 install --upgrade sphinx sphinx-argparse sphinx_rtd_theme pytest
#    - pip3 install -e ./
    - apt-get install -y python3-tk  build-essential libfontconfig1 mesa-common-dev libglu1-mesa-dev libgl1-mesa-glx
    - apt-get install -y qtmultimedia5-dev libqt5multimedia5-plugins libqt5svg5-dev libqt5sql5-mysql libqt5websockets5-dev
#    - pip install matplotlib
    - pip3 install brian2
    - pip3 install sparse
    - pip3 install pyqtgraph
    - pip3 install pyqt5
    - export PYTHONPATH="$PYTHONPATH:/builds/vanessa/"

unit-tests:
    stage: test
    script:
        - cd unit_tests/
        - for f in *.py; do python3 "$f"; done

