# use a python enviroment
image: python:3.5

# dependencies
before_script:
    - apt-get update
    - pip install matplotlib
    - pip install brian2
    - pip install sparse
    - apt-get install -y python3-tk
    - pip install pyqtgraph
    - pip3 install pyqt5
    - export PYTHONPATH="$PYTHONPATH:/builds/:$PWD"
    - echo $PYTHONPATH
    - export PYTHONPATH=$CI_PROJECT_DIR
    - echo $PYTHONPATH

unit-tests:
    stage: test
    script:
        - cd unit_tests/
        - python test_wta.py

