# use a python enviroment
image: python:3.5

# dependencies
before_script:
    - apt-get update
    - apt-get install -y python3-tk  build-essential libfontconfig1 mesa-common-dev libglu1-mesa-dev libgl1-mesa-glx
    - apt-get install -y qtmultimedia5-dev libqt5multimedia5-plugins libqt5svg5-dev libqt5sql5-mysql libqt5websockets5-dev
    - pip install matplotlib
    - pip install brian2
    - pip install sparse
    - pip install pyqtgraph
    - pip install pyqt5
    - mkdir /builds/vanessa/tmp/
    - chmod -R 0700 /builds/vanessa/tmp/
    - export PYTHONPATH="$PYTHONPATH:/builds/vanessa/"
    - export XDG_RUNTIME_DIR="/builds/vanessa/tmp/"

unit-tests:
    stage: test
    script:
        - cd unit_tests/
        - python test_wta.py

